server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
security:
  basic:
    enabled: true                # 开启基于http basic的认证
  user:
    name: acc                    # 配置登录的帐号是acc
    password: Passw0rd           # 配置登录的密码是Passw0rd
